apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flash-card-io

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml

commonLabels:
  app: flash-card-io

images:
  - name: ghcr.io/hatip5656/flash-card-io
    newTag: latest
