apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flash-card-io-data
  namespace: flash-card-io
  labels:
    app: flash-card-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
