apiVersion: v1
kind: Secret
metadata:
  name: flash-card-io-secrets
  namespace: flash-card-io
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
  UNSPLASH_ACCESS_KEY: "${UNSPLASH_ACCESS_KEY}"
  EKILEX_API_KEY: "${EKILEX_API_KEY}"
