--liquibase formatted sql

--changeset hatip:013-a1-vocabulary-v2 splitStatements:true failOnError:false
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jooma', 'jooma', 'to drink', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jooma', 'Ma joon.', 'I drink.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jooma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sööma', 'sööma', 'to eat', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sööma', 'Ma söön.', 'I eat.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sööma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-õppima', 'õppima', 'to study', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-õppima', 'Ma õpin.', 'I study.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-õppima');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mängima', 'mängima', 'to play', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mängima', 'Ma mängin.', 'I play.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mängima');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kirjutama', 'kirjutama', 'to write', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kirjutama', 'Ma kirjutan.', 'I write.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kirjutama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lugema', 'lugema', 'to read', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lugema', 'Ma loen.', 'I read.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lugema');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kuulama', 'kuulama', 'to listen', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kuulama', 'Ma kuulan.', 'I listen.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kuulama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vaatama', 'vaatama', 'to watch', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vaatama', 'Ma vaatan.', 'I watch.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vaatama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-koristama', 'koristama', 'to clean', 'temizlemek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-koristama', 'Ma koristan.', 'I clean.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-koristama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-triikima', 'triikima', 'to iron', 'ütülemek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-triikima', 'Ma triigin.', 'I iron.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-triikima');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jalutama', 'jalutama', 'to walk', 'yürümek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jalutama', 'Ma jalutan.', 'I walk.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jalutama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-töötama', 'töötama', 'to work', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-töötama', 'Ma töötan.', 'I work.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-töötama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-laulma', 'laulma', 'to sing', 'şarkı söylemek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-laulma', 'Ma laulan.', 'I sing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-laulma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tantsima', 'tantsima', 'to dance', 'dans etmek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tantsima', 'Ma tantsin.', 'I dance.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tantsima');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-joonistama', 'joonistama', 'to draw', 'çizmek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-joonistama', 'Ma joonistan.', 'I draw.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-joonistama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ujuma', 'ujuma', 'to swim', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-ujuma', 'Ma ujun.', 'I swim.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-ujuma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-küpsetama', 'küpsetama', 'to bake', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-küpsetama', 'Ma küpsetan.', 'I bake.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-küpsetama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-keetma', 'keetma', 'to boil/cook', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-keetma', 'Ma keedan.', 'I boil/cook.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-keetma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõitma', 'sõitma', 'to drive/ride', 'sürmek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sõitma', 'Ma sõidan.', 'I drive/ride.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sõitma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-minema', 'minema', 'to go', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-minema', 'Ma lähen.', 'I go.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-minema');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tulema', 'tulema', 'to come', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tulema', 'Ma tulen.', 'I come.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tulema');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ostma', 'ostma', 'to buy', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-ostma', 'Ma ostan.', 'I buy.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-ostma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müüma', 'müüma', 'to sell', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-müüma', 'Ma müün.', 'I sell.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-müüma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-avama', 'avama', 'to open', 'açmak', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-avama', 'Ma avan.', 'I open.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-avama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sulgema', 'sulgema', 'to close', 'kapatmak', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sulgema', 'Ma sulgen.', 'I close.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sulgema');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mõtlema', 'mõtlema', 'to think', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mõtlema', 'Ma mõtlen.', 'I think.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mõtlema');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-teadma', 'teadma', 'to know', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-teadma', 'Ma tean.', 'I know.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-teadma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-oskama', 'oskama', 'to know how to / be able to', 'yapabilmek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-oskama', 'Ma oskan.', 'I know how / be able to.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-oskama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tahtma', 'tahtma', 'to want', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tahtma', 'Ma tahan.', 'I want.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tahtma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lootma', 'lootma', 'to hope', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lootma', 'Ma loodan.', 'I hope.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lootma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kartma', 'kartma', 'to fear', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kartma', 'Ma kardan.', 'I fear.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kartma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-naerma', 'naerma', 'to laugh', 'gülmek', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-naerma', 'Ma naeran.', 'I laugh.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-naerma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nutma', 'nutma', 'to cry', 'ağlamak', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-nutma', 'Ma nutan.', 'I cry.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-nutma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jääma', 'jääma', 'to stay/remain', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jääma', 'Ma jään.', 'I stay/remain.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jääma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jooksma', 'jooksma', 'to run', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jooksma', 'Ma jooksen.', 'I run.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jooksma');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-unustama', 'unustama', 'to forget', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-unustama', 'Ma unustan.', 'I forget.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-unustama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mäletama', 'mäletama', 'to remember', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mäletama', 'Ma mäletan.', 'I remember.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mäletama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-küsima', 'küsima', 'to ask', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-küsima', 'Ma küsin.', 'I ask.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-küsima');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vastama', 'vastama', 'to answer', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vastama', 'Ma vastan.', 'I answer.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vastama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-alustama', 'alustama', 'to start', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-alustama', 'Ma alustan.', 'I start.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-alustama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jätkama', 'jätkama', 'to continue', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jätkama', 'Ma jätkan.', 'I continue.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jätkama');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-suur', 'suur', 'big', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-suur', 'See on suur õun.', 'This is a big thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-suur');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-väike', 'väike', 'small', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-väike', 'See on väike maja.', 'This is a small thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-väike');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kallis', 'kallis', 'expensive/dear', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kallis', 'See on kallis auto.', 'This is a expensive/dear thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kallis');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-odav', 'odav', 'cheap', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-odav', 'See on odav pintsak.', 'This is a cheap thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-odav');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ilus', 'ilus', 'beautiful', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-ilus', 'See on ilus linn.', 'This is a beautiful thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-ilus');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kole', 'kole', 'ugly', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kole', 'See on kole hoone.', 'This is a ugly thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kole');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tark', 'tark', 'clever/smart', 'akıllı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tark', 'See on tark loom.', 'This is a clever/smart thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tark');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rumal', 'rumal', 'dumb/foolish', 'aptal', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-rumal', 'See on rumal laps.', 'This is a dumb/foolish thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-rumal');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-noor', 'noor', 'young', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-noor', 'See on noor mees.', 'This is a young thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-noor');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vana', 'vana', 'old', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vana', 'See on vana naine.', 'This is a old thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vana');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-soe', 'soe', 'warm', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-soe', 'See on soe ilm.', 'This is a warm thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-soe');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-külm', 'külm', 'cold', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-külm', 'See on külm päev.', 'This is a cold thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-külm');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kuum', 'kuum', 'hot', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kuum', 'See on kuum suvi.', 'This is a hot thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kuum');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-palav', 'palav', 'scorching/hot', 'bunaltıcı sıcak', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-palav', 'See on palav päev.', 'This is a scorching/hot thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-palav');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sinine', 'sinine', 'blue', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sinine', 'See on sinine kleit.', 'This is a blue thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sinine');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-punane', 'punane', 'red', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-punane', 'See on punane õhupall.', 'This is a red thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-punane');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kollane', 'kollane', 'yellow', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kollane', 'See on kollane leht.', 'This is a yellow thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kollane');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-roosa', 'roosa', 'pink', 'pembe', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-roosa', 'See on roosa roos.', 'This is a pink thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-roosa');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pruun', 'pruun', 'brown', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pruun', 'See on pruun laud.', 'This is a brown thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pruun');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-must', 'must', 'black', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-must', 'See on must kass.', 'This is a black thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-must');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-valge', 'valge', 'white', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-valge', 'See on valge lumi.', 'This is a white thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-valge');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-hele', 'hele', 'light', 'açık (renk)', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-hele', 'See on hele sein.', 'This is a light thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-hele');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tume', 'tume', 'dark', 'koyu', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tume', 'See on tume taevas.', 'This is a dark thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tume');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kiire', 'kiire', 'fast', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kiire', 'See on kiire rong.', 'This is a fast thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kiire');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-aeglane', 'aeglane', 'slow', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-aeglane', 'See on aeglane auto.', 'This is a slow thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-aeglane');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pikk', 'pikk', 'long', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pikk', 'See on pikk tee.', 'This is a long thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pikk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lühike', 'lühike', 'short', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lühike', 'See on lühike kiri.', 'This is a short thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lühike');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tugev', 'tugev', 'strong', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tugev', 'See on tugev mees.', 'This is a strong thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tugev');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nõrk', 'nõrk', 'weak', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-nõrk', 'See on nõrk lamp.', 'This is a weak thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-nõrk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-uus', 'uus', 'new', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-uus', 'See on uus telefon.', 'This is a new thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-uus');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rõõmus', 'rõõmus', 'happy', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-rõõmus', 'See on rõõmus laps.', 'This is a happy thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-rõõmus');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kurb', 'kurb', 'sad', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kurb', 'See on kurb päev.', 'This is a sad thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kurb');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-naljakas', 'naljakas', 'funny', 'komik', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-naljakas', 'See on naljakas film.', 'This is a funny thing.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-naljakas');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vesi', 'vesi', 'water', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vesi', 'Ma ostan vett.', 'I buy water.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vesi');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mesi', 'mesi', 'honey', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mesi', 'Ma ostan mett.', 'I buy honey.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mesi');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kohv', 'kohv', 'coffee', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kohv', 'Ma ostan kohvi.', 'I buy coffee.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kohv');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-suhkur', 'suhkur', 'sugar', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-suhkur', 'Ma ostan suhkrut.', 'I buy sugar.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-suhkur');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sool', 'sool', 'salt', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sool', 'Ma ostan soola.', 'I buy salt.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sool');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jahu', 'jahu', 'flour', 'un', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jahu', 'Ma ostan jahu.', 'I buy flour.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jahu');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-piim', 'piim', 'milk', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-piim', 'Ma ostan piima.', 'I buy milk.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-piim');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-või', 'või', 'butter', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-või', 'Ma ostan võid.', 'I buy butter.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-või');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-muna', 'muna', 'egg', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-muna', 'Ma ostan muna.', 'I buy egg.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-muna');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-liha', 'liha', 'meat', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-liha', 'Ma ostan liha.', 'I buy meat.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-liha');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kala', 'kala', 'fish', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kala', 'Ma ostan kala.', 'I buy fish.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kala');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-riis', 'riis', 'rice', 'pirinç', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-riis', 'Ma ostan riisi.', 'I buy rice.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-riis');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-makaron', 'makaron', 'pasta/macaroni', 'makarna', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-makaron', 'Ma ostan makarone.', 'I buy pasta/macaroni.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-makaron');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-juust', 'juust', 'cheese', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-juust', 'Ma ostan juustu.', 'I buy cheese.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-juust');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vorst', 'vorst', 'sausage', 'sosis', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vorst', 'Ma ostan vorsti.', 'I buy sausage.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vorst');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-õun', 'õun', 'apple', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-õun', 'Ma ostan õuna.', 'I buy apple.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-õun');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pirn', 'pirn', 'pear', 'armut', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pirn', 'Ma ostan pirni.', 'I buy pear.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pirn');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-banaan', 'banaan', 'banana', 'muz', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-banaan', 'Ma ostan banaani.', 'I buy banana.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-banaan');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-apelsin', 'apelsin', 'orange', 'portakal', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-apelsin', 'Ma ostan apelsini.', 'I buy orange.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-apelsin');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-viinamari', 'viinamari', 'grape', 'üzüm', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-viinamari', 'Ma ostan viinamarja.', 'I buy grape.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-viinamari');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kurk', 'kurk', 'cucumber', 'salatalık', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kurk', 'Ma ostan kurki.', 'I buy cucumber.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kurk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tomat', 'tomat', 'tomato', 'domates', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tomat', 'Ma ostan tomatit.', 'I buy tomato.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tomat');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kartul', 'kartul', 'potato', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kartul', 'Ma ostan kartulit.', 'I buy potato.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kartul');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-porgand', 'porgand', 'carrot', 'havuç', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-porgand', 'Ma ostan porgandit.', 'I buy carrot.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-porgand');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kapsas', 'kapsas', 'cabbage', 'lahana', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kapsas', 'Ma ostan kapsast.', 'I buy cabbage.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kapsas');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-seen', 'seen', 'mushroom', 'mantar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-seen', 'Ma ostan seent.', 'I buy mushroom.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-seen');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mais', 'mais', 'corn', 'mısır', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mais', 'Ma ostan maisi.', 'I buy corn.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mais');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-hernes', 'hernes', 'pea', 'bezelye', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-hernes', 'Ma ostan hernest.', 'I buy pea.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-hernes');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mandel', 'mandel', 'almond', 'badem', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mandel', 'Ma ostan mandlit.', 'I buy almond.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mandel');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pähkel', 'pähkel', 'nut', 'fındık', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pähkel', 'Ma ostan pähklit.', 'I buy nut.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pähkel');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rosin', 'rosin', 'raisin', 'kuru üzüm', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-rosin', 'Ma ostan rosinaid.', 'I buy raisin.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-rosin');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jogurt', 'jogurt', 'yogurt', 'yoğurt', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jogurt', 'Ma ostan jogurtit.', 'I buy yogurt.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jogurt');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pea', 'pea', 'head', 'baş', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pea', 'See on minu pea', 'This is my head', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pea');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-juuksed', 'juuksed', 'hair', 'saç', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-juuksed', 'Need on minu juuksed', 'This is my hair', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-juuksed');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-silmad', 'silmad', 'eyes', 'gözler', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-silmad', 'Need on minu silmad', 'These are my eyes', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-silmad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõrvad', 'kõrvad', 'ears', 'kulaklar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kõrvad', 'Need on minu kõrvad', 'These are my ears', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kõrvad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nina', 'nina', 'nose', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-nina', 'See on minu nina.', 'This is my nose.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-nina');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-suu', 'suu', 'mouth', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-suu', 'See on minu suu', 'This is my mouth', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-suu');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kael', 'kael', 'neck', 'boyun', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kael', 'See on minu kael', 'This is my neck', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kael');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-keha', 'keha', 'body', 'vücut', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-keha', 'See on minu keha.', 'This is my body.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-keha');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-õlad', 'õlad', 'shoulders', 'omuzlar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-õlad', 'Need on minu õlad.', 'These are my shoulders.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-õlad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rind', 'rind', 'chest', 'göğüs', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-rind', 'See on minu rind', 'This is my chest', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-rind');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-selg', 'selg', 'back', 'sırt', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-selg', 'See on minu selg', 'This is my back', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-selg');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõht', 'kõht', 'stomach', 'karın', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kõht', 'See on minu kõht', 'This is my stomach', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kõht');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-käed', 'käed', 'arms/hands', 'eller', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-käed', 'Need on minu käed', 'These are my arms', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-käed');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jalad', 'jalad', 'legs/feet', 'bacaklar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jalad', 'Need on minu jalad', 'These are my legs', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jalad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõrmed', 'sõrmed', 'fingers', 'parmaklar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sõrmed', 'Need on minu sõrmed.', 'These are my fingers.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sõrmed');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-varbad', 'varbad', 'toes', 'ayak parmakları', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-varbad', 'Need on minu varbad', 'These are my toes', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-varbad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-arst', 'arst', 'doctor', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-arst', 'Ma töötan arstina.', 'I work as a doctor.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-arst');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kokk', 'kokk', 'cook/chef', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kokk', 'Ma töötan kokana.', 'I work as a cook/chef.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kokk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-õpetaja', 'õpetaja', 'teacher', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-õpetaja', 'Ma töötan õpetajana.', 'I work as a teacher.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-õpetaja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-juuksur', 'juuksur', 'hairdresser', 'kuaför', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-juuksur', 'Ma töötan juuksurina.', 'I work as a hairdresser.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-juuksur');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-taksojuht', 'taksojuht', 'taxi driver', 'taksi şoförü', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-taksojuht', 'Ma töötan taksojuhina.', 'I work as a taxi driver.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-taksojuht');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müüja', 'müüja', 'salesperson/shop assistant', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-müüja', 'Ma töötan müüjana.', 'I work as a salesperson/shop assistant.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-müüja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sekretär', 'sekretär', 'secretary', 'sekreter', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sekretär', 'Ma töötan sekretärina.', 'I work as a secretary.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sekretär');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-elektrik', 'elektrik', 'electrician', 'elektrikçi', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-elektrik', 'Ma töötan elektrikuna.', 'I work as a electrician.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-elektrik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pagar', 'pagar', 'baker', 'fırıncı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-pagar', 'Ma töötan pagarina.', 'I work as a baker.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-pagar');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tõlk', 'tõlk', 'translator', 'tercüman', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tõlk', 'Ma töötan tõlgina.', 'I work as a translator.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tõlk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-näitleja', 'näitleja', 'actor/actress', 'oyuncu', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-näitleja', 'Ma töötan näitlejana.', 'I work as a actor/actress.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-näitleja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-politseinik', 'politseinik', 'police officer', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-politseinik', 'Ma töötan politseinikuna.', 'I work as a police officer.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-politseinik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tuletõrjuja', 'tuletõrjuja', 'firefighter', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tuletõrjuja', 'Ma töötan tuletõrjujana.', 'I work as a firefighter.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tuletõrjuja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-aednik', 'aednik', 'gardener', 'bahçıvan', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-aednik', 'Ma töötan aednikuna.', 'I work as a gardener.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-aednik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-raamatupidaja', 'raamatupidaja', 'accountant', 'muhasebeci', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-raamatupidaja', 'Ma töötan raamatupidajana.', 'I work as a accountant.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-raamatupidaja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-turvamees', 'turvamees', 'security guard', 'güvenlik', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-turvamees', 'Ma töötan turvamehena.', 'I work as a security guard.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-turvamees');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kunstnik', 'kunstnik', 'artist', 'sanatçı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kunstnik', 'Ma töötan kunstnikuna.', 'I work as a artist.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kunstnik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-muusik', 'muusik', 'musician', 'müzisyen', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-muusik', 'Ma töötan muusikuna.', 'I work as a musician.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-muusik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tantsija', 'tantsija', 'dancer', 'dansçı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tantsija', 'Ma töötan tantsijana.', 'I work as a dancer.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tantsija');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-fotograaf', 'fotograaf', 'photographer', 'fotoğrafçı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-fotograaf', 'Ma töötan fotograafina.', 'I work as a photographer.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-fotograaf');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-arhivaar', 'arhivaar', 'archivist', 'arşivci', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-arhivaar', 'Ma töötan arhivaarina.', 'I work as a archivist.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-arhivaar');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-meremees', 'meremees', 'sailor', 'denizci', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-meremees', 'Ma töötan meremehena.', 'I work as a sailor.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-meremees');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-farmatseut', 'farmatseut', 'pharmacist', 'eczacı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-farmatseut', 'Ma töötan farmatseudina.', 'I work as a pharmacist.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-farmatseut');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lastehoidja', 'lastehoidja', 'babysitter', 'çocuk bakıcısı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lastehoidja', 'Ma töötan lastehoidjana.', 'I work as a babysitter.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lastehoidja');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jope', 'jope', 'jacket', 'mont', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-jope', 'Tal on jope seljas.', 'He/she has a jacket on the back.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-jope');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kampsun', 'kampsun', 'sweater', 'kazak', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kampsun', 'Tal on kampsun seljas.', 'He/she has a sweater on the back.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kampsun');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-särk', 'särk', 'shirt', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-särk', 'Tal on särk seljas.', 'He/she has a shirt on the back.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-särk');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müts', 'müts', 'hat/cap', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-müts', 'Tal on müts peas.', 'He/she has a hat/cap on the head.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-müts');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kiiver', 'kiiver', 'helmet', 'kask', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kiiver', 'Tal on kiiver peas.', 'He/she has a helmet on the head.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kiiver');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kapuuts', 'kapuuts', 'hood', 'kapüşon', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kapuuts', 'Tal on kapuuts peas.', 'He/she has a hood on the head.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kapuuts');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sall', 'sall', 'scarf', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sall', 'Tal on sall kaelas.', 'He/she has a scarf around the neck.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sall');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lips', 'lips', 'tie', 'kravat', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lips', 'Tal on lips kaelas.', 'He/she has a tie around the neck.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lips');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kaelakee', 'kaelakee', 'necklace', 'kolye', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kaelakee', 'Tal on kaelakee kaelas.', 'He/she has a necklace around the neck.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kaelakee');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-prillid', 'prillid', 'glasses', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-prillid', 'Tal on prillid ees.', 'He/she has a glasses on the face.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-prillid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-päikeseprillid', 'päikeseprillid', 'sunglasses', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-päikeseprillid', 'Tal on päikeseprillid ees.', 'He/she has a sunglasses on the face.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-päikeseprillid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mask', 'mask', 'mask', 'maske', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-mask', 'Tal on mask ees.', 'He/she has a mask on the face.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-mask');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõrvarõngas', 'kõrvarõngas', 'earring', 'küpe', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kõrvarõngas', 'Tal on kõrvarõngas kõrvas.', 'He/she has a earring in the ear.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kõrvarõngas');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kuuldeaparaat', 'kuuldeaparaat', 'hearing aid', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kuuldeaparaat', 'Tal on kuuldeaparaat kõrvas.', 'He/she has a hearing aid in the ear.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kuuldeaparaat');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ninaneet', 'ninaneet', 'nose ring', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-ninaneet', 'Tal on ninaneet ninas.', 'He/she has a nose ring in the nose.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-ninaneet');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõrmus', 'sõrmus', 'ring', 'yüzük', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sõrmus', 'Tal on sõrmus sõrmes.', 'He/she has a ring on the finger.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sõrmus');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nutisõrmus', 'nutisõrmus', 'smart ring', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-nutisõrmus', 'Tal on nutisõrmus sõrmes.', 'He/she has a smart ring on the finger.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-nutisõrmus');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vihmavari', 'vihmavari', 'umbrella', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vihmavari', 'Tal on vihmavari käes.', 'He/she has a umbrella in the hand.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vihmavari');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kott', 'kott', 'bag', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-kott', 'Tal on kott käes.', 'He/she has a bag in the hand.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-kott');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-telefon', 'telefon', 'phone', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-telefon', 'Tal on telefon käes.', 'He/she has a phone in the hand.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-telefon');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-püksid', 'püksid', 'pants', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-püksid', 'Tal on püksid jalas.', 'He/she has a pants on the legs.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-püksid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lühikesed-püksid', 'lühikesed püksid', 'shorts', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-lühikesed-püksid', 'Tal on lühikesed püksid jalas.', 'He/she has a shorts on the legs.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-lühikesed-püksid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-retuusid', 'retuusid', 'leggings', 'taytlar', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-retuusid', 'Tal on retuusid jalas.', 'He/she has a leggings on the legs.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-retuusid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-saapad', 'saapad', 'boots', 'çizmeler', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-saapad', 'Tal on saapad jalas.', 'He/she has a boots on the feet.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-saapad');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tossud', 'tossud', 'sneakers', 'spor ayakkabı', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-tossud', 'Tal on tossud jalas.', 'He/she has a sneakers on the feet.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-tossud');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sandaalid', 'sandaalid', 'sandals', 'sandaletler', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sandaalid', 'Tal on sandaalid jalas.', 'He/she has a sandals on the feet.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sandaalid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sokid', 'sokid', 'socks', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-sokid', 'Tal on sokid jalas.', 'He/she has a socks on the feet.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-sokid');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vihmakeep', 'vihmakeep', 'raincoat', 'yağmurluk', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-vihmakeep', 'Tal on vihmakeep seljas.', 'He/she has a raincoat on the back.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-vihmakeep');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rätik', 'rätik', 'towel', 'havlu', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-rätik', 'Tal on rätik kaelas.', 'He/she has a towel around the neck.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-rätik');
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-näomaaling', 'näomaaling', 'face paint', '', 'A1') ON CONFLICT DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) SELECT 'a1-näomaaling', 'Tal on näomaaling ees.', 'He/she has a face paint on the face.', '', 0 WHERE EXISTS (SELECT 1 FROM words WHERE id = 'a1-näomaaling');

--changeset hatip:013-a1-grammar-lessons-v2 splitStatements:true failOnError:false
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-telling-time', 'A1', 'Telling Time (Mis kell on?)', 'Saat Söyleme (Mis kell on?)', 'Telling Time in Estonian\n\nFull hours: Kell on uks. (1 o''''clock)\nHalf hours (pool = half BEFORE next hour):\n6:30 = pool seitse, 12:30 = pool uks\nQuarter past: 1:15 = veerand kaks\nQuarter to: 1:45 = kolmveerand kaks\n\nEstonian counts toward the NEXT hour!', 'Estoncada Saat Soyleme\n\nTam saatler: Kell on uks. (Saat 1)\nBucuklar (pool = sonraki saatin yarisi):\n6:30 = pool seitse, 12:30 = pool uks\nCeyrek gece: 1:15 = veerand kaks\nCeyrek kala: 1:45 = kolmveerand kaks\n\nEstonca sonraki saate gore sayar!') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-clothing-locations', 'A1', 'Clothing Grammar (Where is it worn?)', 'Kiyafet Grameri (Nereye giyilir?)', 'Where Clothing is Worn\n\npeas (on head): muts, kiiver\nkaelas (around neck): sall, lips\nseljas (on torso): sark, kampsun, jope\njalas (on legs/feet): puksid, saapad\nkaes (in hands): kindad, vihmavari\nees (on face): prillid, mask\n\nTal on muts peas. Tal on jope seljas.', 'Kiyafetler Nereye Giyilir?\n\npeas (basta): muts, kiiver\nkaelas (boyunda): sall, lips\nseljas (sirtta): sark, kampsun, jope\njalas (bacaklarda): puksid, saapad\nkaes (ellerde): kindad, vihmavari\nees (yuzde): prillid, mask\n\nTal on muts peas. Tal on jope seljas.') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-comitative-abessive', 'A1', 'With (-ga) and Without (-ta)', 'Ile (-ga) ve Siz (-ta)', '-ga (with): add to genitive form\nauto -> autoga, piim -> piimaga, sina -> sinuga\nMa joon kohvi piimaga. Ma soidan autoga.\n\n-ta (without): add to genitive form\nauto -> autota, suhkur -> suhkruta\nKohv suhkruta, palun. Ma olen ilma autota.', '-ga (ile): tamlayan haline eklenir\nauto -> autoga, piim -> piimaga, sina -> sinuga\nMa joon kohvi piimaga. Ma soidan autoga.\n\n-ta (siz): tamlayan haline eklenir\nauto -> autota, suhkur -> suhkruta\nKohv suhkruta, palun. Ma olen ilma autota.') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-ma-da-infinitive', 'A1', 'MA vs DA Infinitive', 'MA ve DA Mastar Sistemi', 'MA-infinitive: after movement/obligation verbs\nMa lahen oppima. Ma hakkan tootama.\n\nDA-infinitive: after desire/feeling/ability verbs\nMa tahan oppida. Mulle meeldib tantsida. Ma oskan ujuda.\n\nPairs: jooma/juua, sooma/suua, oppima/oppida, minema/minna', 'MA-mastar: hareket/zorunluluk fiillerinden sonra\nMa lahen oppima. Ma hakkan tootama.\n\nDA-mastar: istek/duygu/yetenek fiillerinden sonra\nMa tahan oppida. Mulle meeldib tantsida. Ma oskan ujuda.\n\nCiftler: jooma/juua, sooma/suua, oppima/oppida, minema/minna') ON CONFLICT (id) DO NOTHING;
