--liquibase formatted sql

--changeset hatip:013-a1-vocabulary splitStatements:true
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kuulama', 'kuulama', 'to listen', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kuulama', 'Ma kuulan.', 'I listen.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-koristama', 'koristama', 'to clean', 'temizlemek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-koristama', 'Ma koristan.', 'I clean.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-triikima', 'triikima', 'to iron', 'ütülemek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-triikima', 'Ma triigin.', 'I iron.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jalutama', 'jalutama', 'to walk', 'yürümek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jalutama', 'Ma jalutan.', 'I walk.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-laulma', 'laulma', 'to sing', 'şarkı söylemek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-laulma', 'Ma laulan.', 'I sing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tantsima', 'tantsima', 'to dance', 'dans etmek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tantsima', 'Ma tantsin.', 'I dance.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-joonistama', 'joonistama', 'to draw', 'çizmek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-joonistama', 'Ma joonistan.', 'I draw.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ujuma', 'ujuma', 'to swim', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-ujuma', 'Ma ujun.', 'I swim.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-küpsetama', 'küpsetama', 'to bake', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-küpsetama', 'Ma küpsetan.', 'I bake.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-keetma', 'keetma', 'to boil/cook', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-keetma', 'Ma keedan.', 'I boil/cook.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõitma', 'sõitma', 'to drive/ride', 'sürmek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sõitma', 'Ma sõidan.', 'I drive/ride.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müüma', 'müüma', 'to sell', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-müüma', 'Ma müün.', 'I sell.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-avama', 'avama', 'to open', 'açmak', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-avama', 'Ma avan.', 'I open.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sulgema', 'sulgema', 'to close', 'kapatmak', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sulgema', 'Ma sulgen.', 'I close.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-oskama', 'oskama', 'to know how to / be able to', 'yapabilmek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-oskama', 'Ma oskan.', 'I know how / be able to.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lootma', 'lootma', 'to hope', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-lootma', 'Ma loodan.', 'I hope.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kartma', 'kartma', 'to fear', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kartma', 'Ma kardan.', 'I fear.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-naerma', 'naerma', 'to laugh', 'gülmek', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-naerma', 'Ma naeran.', 'I laugh.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nutma', 'nutma', 'to cry', 'ağlamak', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-nutma', 'Ma nutan.', 'I cry.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jääma', 'jääma', 'to stay/remain', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jääma', 'Ma jään.', 'I stay/remain.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jooksma', 'jooksma', 'to run', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jooksma', 'Ma jooksen.', 'I run.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mäletama', 'mäletama', 'to remember', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-mäletama', 'Ma mäletan.', 'I remember.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-küsima', 'küsima', 'to ask', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-küsima', 'Ma küsin.', 'I ask.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vastama', 'vastama', 'to answer', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-vastama', 'Ma vastan.', 'I answer.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jätkama', 'jätkama', 'to continue', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jätkama', 'Ma jätkan.', 'I continue.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kole', 'kole', 'ugly', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kole', 'See on kole hoone.', 'This is a ugly thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tark', 'tark', 'clever/smart', 'akıllı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tark', 'See on tark loom.', 'This is a clever/smart thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rumal', 'rumal', 'dumb/foolish', 'aptal', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-rumal', 'See on rumal laps.', 'This is a dumb/foolish thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-palav', 'palav', 'scorching/hot', 'bunaltıcı sıcak', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-palav', 'See on palav päev.', 'This is a scorching/hot thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-roosa', 'roosa', 'pink', 'pembe', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-roosa', 'See on roosa roos.', 'This is a pink thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-hele', 'hele', 'light', 'açık (renk)', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-hele', 'See on hele sein.', 'This is a light thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tume', 'tume', 'dark', 'koyu', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tume', 'See on tume taevas.', 'This is a dark thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rõõmus', 'rõõmus', 'happy', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-rõõmus', 'See on rõõmus laps.', 'This is a happy thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kurb', 'kurb', 'sad', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kurb', 'See on kurb päev.', 'This is a sad thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-naljakas', 'naljakas', 'funny', 'komik', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-naljakas', 'See on naljakas film.', 'This is a funny thing.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mesi', 'mesi', 'honey', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-mesi', 'Ma ostan mett.', 'I buy honey.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jahu', 'jahu', 'flour', 'un', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jahu', 'Ma ostan jahu.', 'I buy flour.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-riis', 'riis', 'rice', 'pirinç', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-riis', 'Ma ostan riisi.', 'I buy rice.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-makaron', 'makaron', 'pasta/macaroni', 'makarna', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-makaron', 'Ma ostan makarone.', 'I buy pasta/macaroni.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vorst', 'vorst', 'sausage', 'sosis', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-vorst', 'Ma ostan vorsti.', 'I buy sausage.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pirn', 'pirn', 'pear', 'armut', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-pirn', 'Ma ostan pirni.', 'I buy pear.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-banaan', 'banaan', 'banana', 'muz', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-banaan', 'Ma ostan banaani.', 'I buy banana.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-apelsin', 'apelsin', 'orange', 'portakal', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-apelsin', 'Ma ostan apelsini.', 'I buy orange.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-viinamari', 'viinamari', 'grape', 'üzüm', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-viinamari', 'Ma ostan viinamarja.', 'I buy grape.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kurk', 'kurk', 'cucumber', 'salatalık', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kurk', 'Ma ostan kurki.', 'I buy cucumber.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tomat', 'tomat', 'tomato', 'domates', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tomat', 'Ma ostan tomatit.', 'I buy tomato.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-porgand', 'porgand', 'carrot', 'havuç', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-porgand', 'Ma ostan porgandit.', 'I buy carrot.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kapsas', 'kapsas', 'cabbage', 'lahana', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kapsas', 'Ma ostan kapsast.', 'I buy cabbage.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-seen', 'seen', 'mushroom', 'mantar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-seen', 'Ma ostan seent.', 'I buy mushroom.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mais', 'mais', 'corn', 'mısır', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-mais', 'Ma ostan maisi.', 'I buy corn.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-hernes', 'hernes', 'pea', 'bezelye', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-hernes', 'Ma ostan hernest.', 'I buy pea.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mandel', 'mandel', 'almond', 'badem', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-mandel', 'Ma ostan mandlit.', 'I buy almond.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pähkel', 'pähkel', 'nut', 'fındık', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-pähkel', 'Ma ostan pähklit.', 'I buy nut.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rosin', 'rosin', 'raisin', 'kuru üzüm', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-rosin', 'Ma ostan rosinaid.', 'I buy raisin.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jogurt', 'jogurt', 'yogurt', 'yoğurt', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jogurt', 'Ma ostan jogurtit.', 'I buy yogurt.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-juuksed', 'juuksed', 'hair', 'saç', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-juuksed', 'Need on minu juuksed', 'This is my hair', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-silmad', 'silmad', 'eyes', 'gözler', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-silmad', 'Need on minu silmad', 'These are my eyes', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõrvad', 'kõrvad', 'ears', 'kulaklar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kõrvad', 'Need on minu kõrvad', 'These are my ears', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kael', 'kael', 'neck', 'boyun', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kael', 'See on minu kael', 'This is my neck', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-keha', 'keha', 'body', 'vücut', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-keha', 'See on minu keha.', 'This is my body.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-õlad', 'õlad', 'shoulders', 'omuzlar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-õlad', 'Need on minu õlad.', 'These are my shoulders.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rind', 'rind', 'chest', 'göğüs', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-rind', 'See on minu rind', 'This is my chest', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-selg', 'selg', 'back', 'sırt', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-selg', 'See on minu selg', 'This is my back', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõht', 'kõht', 'stomach', 'karın', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kõht', 'See on minu kõht', 'This is my stomach', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-käed', 'käed', 'arms/hands', 'eller', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-käed', 'Need on minu käed', 'These are my arms', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jalad', 'jalad', 'legs/feet', 'bacaklar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jalad', 'Need on minu jalad', 'These are my legs', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõrmed', 'sõrmed', 'fingers', 'parmaklar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sõrmed', 'Need on minu sõrmed.', 'These are my fingers.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-varbad', 'varbad', 'toes', 'ayak parmakları', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-varbad', 'Need on minu varbad', 'These are my toes', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kokk', 'kokk', 'cook/chef', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kokk', 'Ma töötan kokana.', 'I work as a cook/chef.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-juuksur', 'juuksur', 'hairdresser', 'kuaför', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-juuksur', 'Ma töötan juuksurina.', 'I work as a hairdresser.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-taksojuht', 'taksojuht', 'taxi driver', 'taksi şoförü', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-taksojuht', 'Ma töötan taksojuhina.', 'I work as a taxi driver.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müüja', 'müüja', 'salesperson/shop assistant', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-müüja', 'Ma töötan müüjana.', 'I work as a salesperson/shop assistant.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sekretär', 'sekretär', 'secretary', 'sekreter', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sekretär', 'Ma töötan sekretärina.', 'I work as a secretary.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-elektrik', 'elektrik', 'electrician', 'elektrikçi', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-elektrik', 'Ma töötan elektrikuna.', 'I work as a electrician.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-pagar', 'pagar', 'baker', 'fırıncı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-pagar', 'Ma töötan pagarina.', 'I work as a baker.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tõlk', 'tõlk', 'translator', 'tercüman', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tõlk', 'Ma töötan tõlgina.', 'I work as a translator.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-näitleja', 'näitleja', 'actor/actress', 'oyuncu', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-näitleja', 'Ma töötan näitlejana.', 'I work as a actor/actress.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-politseinik', 'politseinik', 'police officer', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-politseinik', 'Ma töötan politseinikuna.', 'I work as a police officer.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tuletõrjuja', 'tuletõrjuja', 'firefighter', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tuletõrjuja', 'Ma töötan tuletõrjujana.', 'I work as a firefighter.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-aednik', 'aednik', 'gardener', 'bahçıvan', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-aednik', 'Ma töötan aednikuna.', 'I work as a gardener.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-raamatupidaja', 'raamatupidaja', 'accountant', 'muhasebeci', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-raamatupidaja', 'Ma töötan raamatupidajana.', 'I work as a accountant.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-turvamees', 'turvamees', 'security guard', 'güvenlik', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-turvamees', 'Ma töötan turvamehena.', 'I work as a security guard.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kunstnik', 'kunstnik', 'artist', 'sanatçı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kunstnik', 'Ma töötan kunstnikuna.', 'I work as a artist.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-muusik', 'muusik', 'musician', 'müzisyen', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-muusik', 'Ma töötan muusikuna.', 'I work as a musician.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tantsija', 'tantsija', 'dancer', 'dansçı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tantsija', 'Ma töötan tantsijana.', 'I work as a dancer.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-fotograaf', 'fotograaf', 'photographer', 'fotoğrafçı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-fotograaf', 'Ma töötan fotograafina.', 'I work as a photographer.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-arhivaar', 'arhivaar', 'archivist', 'arşivci', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-arhivaar', 'Ma töötan arhivaarina.', 'I work as a archivist.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-meremees', 'meremees', 'sailor', 'denizci', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-meremees', 'Ma töötan meremehena.', 'I work as a sailor.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-farmatseut', 'farmatseut', 'pharmacist', 'eczacı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-farmatseut', 'Ma töötan farmatseudina.', 'I work as a pharmacist.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lastehoidja', 'lastehoidja', 'babysitter', 'çocuk bakıcısı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-lastehoidja', 'Ma töötan lastehoidjana.', 'I work as a babysitter.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-jope', 'jope', 'jacket', 'mont', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-jope', 'Tal on jope seljas.', 'He/she has a jacket on the back.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kampsun', 'kampsun', 'sweater', 'kazak', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kampsun', 'Tal on kampsun seljas.', 'He/she has a sweater on the back.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-särk', 'särk', 'shirt', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-särk', 'Tal on särk seljas.', 'He/she has a shirt on the back.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-müts', 'müts', 'hat/cap', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-müts', 'Tal on müts peas.', 'He/she has a hat/cap on the head.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kiiver', 'kiiver', 'helmet', 'kask', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kiiver', 'Tal on kiiver peas.', 'He/she has a helmet on the head.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kapuuts', 'kapuuts', 'hood', 'kapüşon', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kapuuts', 'Tal on kapuuts peas.', 'He/she has a hood on the head.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sall', 'sall', 'scarf', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sall', 'Tal on sall kaelas.', 'He/she has a scarf around the neck.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lips', 'lips', 'tie', 'kravat', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-lips', 'Tal on lips kaelas.', 'He/she has a tie around the neck.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kaelakee', 'kaelakee', 'necklace', 'kolye', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kaelakee', 'Tal on kaelakee kaelas.', 'He/she has a necklace around the neck.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-prillid', 'prillid', 'glasses', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-prillid', 'Tal on prillid ees.', 'He/she has a glasses on the face.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-päikeseprillid', 'päikeseprillid', 'sunglasses', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-päikeseprillid', 'Tal on päikeseprillid ees.', 'He/she has a sunglasses on the face.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-mask', 'mask', 'mask', 'maske', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-mask', 'Tal on mask ees.', 'He/she has a mask on the face.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kõrvarõngas', 'kõrvarõngas', 'earring', 'küpe', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kõrvarõngas', 'Tal on kõrvarõngas kõrvas.', 'He/she has a earring in the ear.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kuuldeaparaat', 'kuuldeaparaat', 'hearing aid', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kuuldeaparaat', 'Tal on kuuldeaparaat kõrvas.', 'He/she has a hearing aid in the ear.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-ninaneet', 'ninaneet', 'nose ring', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-ninaneet', 'Tal on ninaneet ninas.', 'He/she has a nose ring in the nose.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sõrmus', 'sõrmus', 'ring', 'yüzük', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sõrmus', 'Tal on sõrmus sõrmes.', 'He/she has a ring on the finger.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-nutisõrmus', 'nutisõrmus', 'smart ring', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-nutisõrmus', 'Tal on nutisõrmus sõrmes.', 'He/she has a smart ring on the finger.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vihmavari', 'vihmavari', 'umbrella', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-vihmavari', 'Tal on vihmavari käes.', 'He/she has a umbrella in the hand.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-kott', 'kott', 'bag', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-kott', 'Tal on kott käes.', 'He/she has a bag in the hand.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-püksid', 'püksid', 'pants', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-püksid', 'Tal on püksid jalas.', 'He/she has a pants on the legs.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-lühikesed-püksid', 'lühikesed püksid', 'shorts', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-lühikesed-püksid', 'Tal on lühikesed püksid jalas.', 'He/she has a shorts on the legs.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-retuusid', 'retuusid', 'leggings', 'taytlar', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-retuusid', 'Tal on retuusid jalas.', 'He/she has a leggings on the legs.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-saapad', 'saapad', 'boots', 'çizmeler', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-saapad', 'Tal on saapad jalas.', 'He/she has a boots on the feet.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-tossud', 'tossud', 'sneakers', 'spor ayakkabı', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-tossud', 'Tal on tossud jalas.', 'He/she has a sneakers on the feet.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sandaalid', 'sandaalid', 'sandals', 'sandaletler', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sandaalid', 'Tal on sandaalid jalas.', 'He/she has a sandals on the feet.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-sokid', 'sokid', 'socks', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-sokid', 'Tal on sokid jalas.', 'He/she has a socks on the feet.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-vihmakeep', 'vihmakeep', 'raincoat', 'yağmurluk', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-vihmakeep', 'Tal on vihmakeep seljas.', 'He/she has a raincoat on the back.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-rätik', 'rätik', 'towel', 'havlu', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-rätik', 'Tal on rätik kaelas.', 'He/she has a towel around the neck.', '', 0);
INSERT INTO words (id, estonian, english, turkish, cefr_level) VALUES ('a1-näomaaling', 'näomaaling', 'face paint', '', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO word_sentences (word_id, estonian, english, turkish, sort_order) VALUES ('a1-näomaaling', 'Tal on näomaaling ees.', 'He/she has a face paint on the face.', '', 0);

--changeset hatip:013-a1-grammar-lessons splitStatements:true
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-telling-time', 'A1', 'Telling Time (Mis kell on?)', 'Saat Söyleme (Mis kell on?)', '<b>Telling Time in Estonian</b>\n\n<b>Full hours:</b>\nKell on <code>üks</code>. — It is 1 o''clock.\nKell on <code>kaks</code>. — It is 2 o''clock.\n\n<b>Half hours (pool = half BEFORE next hour):</b>\n6:30 = <code>pool seitse</code> (half before seven)\n12:30 = <code>pool üks</code> (half before one)\n8:30 = <code>pool üheksa</code> (half before nine)\n\n<b>Quarter past (veerand):</b>\n1:15 = <code>veerand kaks</code> (quarter of two)\n3:15 = <code>veerand neli</code> (quarter of four)\n\n<b>Quarter to (kolmveerand):</b>\n1:45 = <code>kolmveerand kaks</code> (three-quarters of two)\n5:45 = <code>kolmveerand kuus</code> (three-quarters of six)\n\n<i>Remember: Estonian counts toward the NEXT hour!</i>', '<b>Estoncada Saat Söyleme</b>\n\n<b>Tam saatler:</b>\nKell on <code>üks</code>. — Saat 1.\nKell on <code>kaks</code>. — Saat 2.\n\n<b>Buçuklar (pool = sonraki saatin yarısı):</b>\n6:30 = <code>pool seitse</code> (yedinin yarısı)\n12:30 = <code>pool üks</code> (birin yarısı)\n\n<b>Çeyrek geçe (veerand):</b>\n1:15 = <code>veerand kaks</code> (ikinin çeyreği)\n\n<b>Çeyrek kala (kolmveerand):</b>\n1:45 = <code>kolmveerand kaks</code> (ikinin üç çeyreği)\n\n<i>Dikkat: Estonca sonraki saate göre sayar!</i>') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-clothing-locations', 'A1', 'Clothing Grammar (Where is it worn?)', 'Kıyafet Grameri (Nereye giyilir?)', '<b>Where Clothing is Worn</b>\n\n<code>peas</code> (on the head): müts, kiiver, kapuuts\n<code>kaelas</code> (around the neck): sall, lips, kaelakee\n<code>seljas</code> (on the back/torso): särk, kampsun, jope\n<code>jalas</code> (on legs/feet): püksid, saapad, sokid\n<code>käes</code> (in the hands): kindad, vihmavari, kott\n<code>ees</code> (on the face): prillid, päikeseprillid, mask\n\n💬 <i>Tal on müts <code>peas</code>.</i> — He has a hat on.\n💬 <i>Tal on jope <code>seljas</code>.</i> — He has a jacket on.\n💬 <i>Tal on prillid <code>ees</code>.</i> — He has glasses on.', '<b>Kıyafetler Nereye Giyilir?</b>\n\n<code>peas</code> (başta): müts, kiiver, kapuuts\n<code>kaelas</code> (boyunda): sall, lips, kaelakee\n<code>seljas</code> (sırtta): särk, kampsun, jope\n<code>jalas</code> (bacaklarda): püksid, saapad, sokid\n<code>käes</code> (ellerde): kindad, vihmavari, kott\n<code>ees</code> (yüzde): prillid, päikeseprillid, mask\n\n💬 <i>Tal on müts <code>peas</code>.</i> — Şapkası var.\n💬 <i>Tal on jope <code>seljas</code>.</i> — Montu var.\n💬 <i>Tal on prillid <code>ees</code>.</i> — Gözlüğü var.') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-comitative-abessive', 'A1', 'With (-ga) & Without (-ta)', 'İle (-ga) ve Sız/Siz (-ta)', '<b>Comitative -ga (with) & Abessive -ta (without)</b>\n\nAdd to the Genitive form:\n\n<b>-ga (with):</b>\nauto → auto<code>ga</code> (by car)\npiim → piima<code>ga</code> (with milk)\nsina → sinu<code>ga</code> (with you)\n\n💬 <i>Ma joon kohvi <code>piimaga</code>.</i> — I drink coffee with milk.\n💬 <i>Ma sõidan <code>autoga</code>.</i> — I travel by car.\n\n<b>-ta (without):</b>\nauto → auto<code>ta</code> (without car)\nsuhkur → suhkru<code>ta</code> (without sugar)\n\n💬 <i>Kohv <code>suhkruta</code>, palun.</i> — Coffee without sugar, please.', '<b>-ga (ile) ve -ta (sız/siz)</b>\n\nİsmin tamlayan haline eklenir:\n\n<b>-ga (ile):</b>\nauto → auto<code>ga</code> (arabayla)\npiim → piima<code>ga</code> (sütle)\nsina → sinu<code>ga</code> (seninle)\n\n💬 <i>Ma joon kohvi <code>piimaga</code>.</i> — Kahveyi sütle içerim.\n\n<b>-ta (sız/siz):</b>\nsuhkur → suhkru<code>ta</code> (şekersiz)\n\n💬 <i>Kohv <code>suhkruta</code>, palun.</i> — Şekersiz kahve, lütfen.') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_lessons (id, cefr_level, topic, topic_tr, content, content_tr) VALUES ('a1-ma-da-infinitive', 'A1', 'MA vs DA Infinitive', 'MA ve DA Mastar Sistemi', '<b>Two Infinitive Forms</b>\n\n<b>MA-infinitive</b> — after movement/obligation verbs:\n💬 <i>Ma lähen <code>õppima</code>.</i> — I go to study.\n💬 <i>Ma hakkan <code>töötama</code>.</i> — I start working.\n\n<b>DA-infinitive</b> — after desire/feeling/ability verbs:\n💬 <i>Ma tahan <code>õppida</code>.</i> — I want to study.\n💬 <i>Mulle meeldib <code>tantsida</code>.</i> — I like to dance.\n💬 <i>Ma oskan <code>ujuda</code>.</i> — I can swim.\n\n<b>Quick pairs:</b>\njooma/juua (drink), sööma/süüa (eat), õppima/õppida (study), minema/minna (go)', '<b>İki Mastar Formu</b>\n\n<b>MA-mastar</b> — hareket/zorunluluk fiillerinden sonra:\n💬 <i>Ma lähen <code>õppima</code>.</i> — Çalışmaya gidiyorum.\n💬 <i>Ma hakkan <code>töötama</code>.</i> — Çalışmaya başlıyorum.\n\n<b>DA-mastar</b> — istek/duygu/yetenek fiillerinden sonra:\n💬 <i>Ma tahan <code>õppida</code>.</i> — Çalışmak istiyorum.\n💬 <i>Mulle meeldib <code>tantsida</code>.</i> — Dans etmeyi severim.\n\n<b>Hızlı çiftler:</b>\njooma/juua (içmek), sööma/süüa (yemek), õppima/õppida (çalışmak), minema/minna (gitmek)') ON CONFLICT (id) DO NOTHING;
